### ISSUE TITLE
pandas==0.20.3 can't be installed on python3.8 + warnings on python3.6

### ISSUE THREAD

**Issue by melissa-hobson** [AlexandrosAntoniadis/ODUSSEAS#5]
I was trying to install the specified pandas version on python3.8, but it's not supported, the pip install fails. I did manage to install it with python3.6, but it throws a LOT of warnings of this type:

> SettingWithCopyWarning: 
> A value is trying to be set on a copy of a slice from a DataFrame
> 

Should I be concerned by these warnings? And would it be possible to upgrade to a 3.8-supported pandas version?

**Comment by AlexandrosAntoniadis** [comment]
> I was trying to install the specified pandas version on python3.8, but it's not supported, the pip install fails. I did manage to install it with python3.6, but it throws a LOT of warnings of this type:
> 
> > SettingWithCopyWarning:
> > A value is trying to be set on a copy of a slice from a DataFrame
> 
> Should I be concerned by these warnings? And would it be possible to upgrade to a 3.8-supported pandas version?

Dear Melissa, 

No, there is no reason to be concerned by these warnings. They do not affect the process and the results.

I have not checked yet the possibility of adapting the code to the python 3.8 version, but I will consider it in the near future.
