### ISSUE TITLE
Code is crashing

### ISSUE THREAD

**Issue by DanielAndreasen** [AlexandrosAntoniadis/ODUSSEAS#7]
Hi Alex,

I'm trying to clean the code, and make it run: `python ODUSSEAS.py` with default values, and the test data. However, it crashes here for me, and I don't understand what you are trying to do:
https://github.com/AlexandrosAntoniadis/ODUSSEAS/blob/master/MachineLearning.py#L80

What is `newdf` supposed to be?

**Comment by DanielAndreasen** [comment]
The code crashes in the same way as in #4. However, I think it is a poor decision to install version 0.20, as that is quite ancient, compared to the newest version 2.2.

I think we need to fix this error for more modern version of pythons, and possibly give information how to install this package in the readme.

Personally I use python 3.12 (latest version), which have many benefits compared to older versions.

Therefore I still need to understand what the purpose of `newdf` is.

**Comment by AlexandrosAntoniadis** [comment]
Hi Daniel,

As answered in a previous issue reporting the same problem, this error can be solved with installing python version 3.6 and the pandas version 0.20, as mentioned in the Installation Requirements at README. 
This is the part of the code we are trying to update for the newest python and pandas package.

This line (that apparently is outdated in the newest version of pandas) is for masking out values of EW measurements which are 0. These refer to possible parts of a spectrum where it may have gaps in its flux and we have pre-connected the parts of the flux by linearly interpolating the 1-D spectrum. So, in order not to consider those zero EW-values of the non-existing absorption lines there, we exclude them from being compared with the machine-learning model.

A manual way to skip these potential flux-gaps in the process, would be to remove from the lines.rdb file the wavelength region of the spectral gap, but having built in the code the existing part where it does not consider zero-EWs of the artificial lines connecting the flux is better.
